spring:
  threads:
    virtual:
      enabled: true    
joinfaces:
  primefaces:
    theme: vela
tomcat:
  version: @tomcat.version@
jetty:
  version: @jetty.version@
undertow:
  version: @undertow.version@
